name: Deploy VuePress

on:
  push:
    branches:
      - main # 当 main 分支有更新时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build VuePress
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        run: |
          cd docs/.vuepress/dist
          git init
          git add -A
          git commit -m 'Deploy to GitHub Pages'
          git push -f git@github.com:Linncharm/Linncharm.github.io.git main
